name: advanced-bedrock-deployment
description: Advanced AWS Bedrock AgentCore deployment with Memory support
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
